/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondesstagiaires;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LANDRY PC
 */
public class Anciens_Stagiaire extends javax.swing.JFrame {
    PreparedStatement pst;
    ResultSet rs;
    Connection con;

    /**
     * Creates new form Anciens_Stagiaire
     */
    public Anciens_Stagiaire() {
        initComponents();
        Table();
    }

     public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/gestion_des_stagiaires","root","");
            
        } catch (Exception e) {
             e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableStagiaire = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtResultat_trouver = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtrechercheStagiaire = new javax.swing.JTextField();
        txtrechercheStagiaire1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 51));
        setFocusTraversalPolicyProvider(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableStagiaire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableStagiaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableStagiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStagiaireMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableStagiaireMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableStagiaire);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1320, 430));

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResultat_trouver.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtResultat_trouver.setForeground(new java.awt.Color(255, 255, 255));
        txtResultat_trouver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResultat_trouver.setText("Resultat");
        jPanel1.add(txtResultat_trouver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 550, 40));

        jButton4.setBackground(new java.awt.Color(0, 51, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("ACTUALISER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 152, 60));

        jButton8.setBackground(new java.awt.Color(0, 51, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("IMPRESSION");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 143, 60));

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestiondesstagiaires/exit.png"))); // NOI18N
        jButton5.setText("RETOUR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 140, 60));

        txtrechercheStagiaire.setBorder(javax.swing.BorderFactory.createTitledBorder("Rechercher stagiaire par nom"));
        txtrechercheStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechercheStagiaireActionPerformed(evt);
            }
        });
        txtrechercheStagiaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrechercheStagiaireKeyReleased(evt);
            }
        });
        jPanel1.add(txtrechercheStagiaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 340, 60));

        txtrechercheStagiaire1.setBorder(javax.swing.BorderFactory.createTitledBorder("Rechercher stagiaire par etablissements"));
        txtrechercheStagiaire1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechercheStagiaire1ActionPerformed(evt);
            }
        });
        txtrechercheStagiaire1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrechercheStagiaire1KeyReleased(evt);
            }
        });
        jPanel1.add(txtrechercheStagiaire1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 310, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestiondesstagiaires/stock-photo-medical-education-health-care-people-and-medicine-concept-group-of-happy-doctors-or-interns-309730637.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 4, 1360, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1350, 610));

        setSize(new java.awt.Dimension(1365, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableStagiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStagiaireMouseClicked

        

    }//GEN-LAST:event_tableStagiaireMouseClicked

    private void tableStagiaireMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStagiaireMousePressed
        

    }//GEN-LAST:event_tableStagiaireMousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
        Table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Anciens_Stagiaire.super.dispose();
        Utilisateur1 log = new  Utilisateur1();
        log.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        MessageFormat header = new MessageFormat("Liste anciens stagiaires");
        MessageFormat footer = new MessageFormat("Page{0,number, integer}");
        try{
            tableStagiaire.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch(java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impresion",e.getMessage());
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtrechercheStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechercheStagiaireActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtrechercheStagiaireActionPerformed

    private void txtrechercheStagiaireKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrechercheStagiaireKeyReleased
        rechercheAncienStagiaire();
    }//GEN-LAST:event_txtrechercheStagiaireKeyReleased

    private void txtrechercheStagiaire1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechercheStagiaire1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercheStagiaire1ActionPerformed

    private void txtrechercheStagiaire1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrechercheStagiaire1KeyReleased
        // TODO add your handling code here:
        rechercheAncienStagiaireParEtablissement();
    }//GEN-LAST:event_txtrechercheStagiaire1KeyReleased

    
      public void rechercheAncienStagiaire() {
    String[] Champ = {"NOM", "PRENOM", "PHONE", "NIVEAU", "DUREE", "TYPE", "NOU", "DATE-D", "DATE-F", "FILIERE", "SERVICE", "DIRECTION", "ETABLISSEMENT", "ENCADREUR", "ID"};
    DefaultTableModel model = new DefaultTableModel(null, Champ);
    try {
        connect con = new connect();
        // Requête SQL pour rechercher un stagiaire par nom dans la table des anciens stagiaires
        pst = con.con.prepareStatement("SELECT * FROM anciens_stagiaires WHERE nomstagiaire LIKE ?");
        pst.setString(1, "%" + txtrechercheStagiaire.getText().trim() + "%"); // Recherche par nom
        rs = pst.executeQuery();
        int i = 0;

        while (rs.next()) {
            String[] afficher = new String[15];
            afficher[0] = rs.getString("nomstagiaire");
            afficher[1] = rs.getString("prenomstagiaire");
            afficher[2] = rs.getString("phone");
            afficher[3] = rs.getString("niveaustagiaire");
            afficher[4] = rs.getString("durée");
            afficher[5] = rs.getString("type");
            afficher[6] = rs.getString("nou");
            afficher[7] = rs.getString("dateD");
            afficher[8] = rs.getString("dateF");
            afficher[9] = rs.getString("filière");
            afficher[10] = rs.getString("service");
            afficher[11] = rs.getString("direction");
            afficher[12] = rs.getString("etablissement");
            afficher[13] = rs.getString("encadreur");
            afficher[14] = rs.getString("idstagiaire");
            
            i++;

            model.addRow(afficher); // Ajout de la ligne dans le tableau
        }

        
        txtResultat_trouver.setText(i + ":Resultat trouver");
        tableStagiaire.setModel(model);// Mise à jour du modèle de la table avec les résultats
    } catch (Exception e) {
        e.printStackTrace(); // Afficher les erreurs en cas de problème
    }
}

 public void rechercheAncienStagiaireParEtablissement() {
    String[] Champ = {"NOM", "PRENOM", "PHONE", "NIVEAU", "DUREE", "TYPE", "NOU", "DATE-D", "DATE-F", "FILIERE", "SERVICE", "DIRECTION", "ETABLISSEMENT", "ENCADREUR", "ID"};
    DefaultTableModel model = new DefaultTableModel(null, Champ);
    try {
        connect con = new connect();
        // Requête SQL pour rechercher un stagiaire par nom dans la table des anciens stagiaires
        pst = con.con.prepareStatement("SELECT * FROM anciens_stagiaires WHERE etablissement LIKE ?");
        pst.setString(1, "%" + txtrechercheStagiaire1.getText().trim() + "%"); // Recherche par nom
        rs = pst.executeQuery();
        int i = 0;

        while (rs.next()) {
            String[] afficher = new String[15];
            afficher[0] = rs.getString("nomstagiaire");
            afficher[1] = rs.getString("prenomstagiaire");
            afficher[2] = rs.getString("phone");
            afficher[3] = rs.getString("niveaustagiaire");
            afficher[4] = rs.getString("durée");
            afficher[5] = rs.getString("type");
            afficher[6] = rs.getString("nou");
            afficher[7] = rs.getString("dateD");
            afficher[8] = rs.getString("dateF");
            afficher[9] = rs.getString("filière");
            afficher[10] = rs.getString("service");
            afficher[11] = rs.getString("direction");
            afficher[12] = rs.getString("etablissement");
            afficher[13] = rs.getString("encadreur");
            afficher[14] = rs.getString("idstagiaire");
            
            i++;

            model.addRow(afficher); // Ajout de la ligne dans le tableau
        }

        tableStagiaire.setModel(model); 
        txtResultat_trouver.setText(i + ":Resultat trouver");
// Mise à jour du modèle de la table avec les résultats
    } catch (Exception e) {
        e.printStackTrace(); // Afficher les erreurs en cas de problème
    }
}

 
     public void Table(){
        String[] stagiaire={"NOM","PRENOM","PHONE","NIVEAU","DUREE","TYPE","NOUVEAU","DATE-D","DATE-F","FILIERE","SERVICE","DIRECTION","ETABLISSEMENT","ENCADREUR","ID"};
        String[] afficher=new String[15];
        DefaultTableModel model= new DefaultTableModel(null, stagiaire);
        try {
                Connect();
        Statement st=(Statement) con.createStatement();
        rs = st.executeQuery("select * from anciens_stagiaires");
        int i = 0;

        while (rs.next()){
        
        afficher[0]=rs.getString("nomstagiaire");
        afficher[1]=rs.getString("prenomstagiaire");
        afficher[2]=rs.getString("phone");
        afficher[3]=rs.getString("niveaustagiaire");
        afficher[4]=rs.getString("durée");
        afficher[5]=rs.getString("type");
        afficher[6]=rs.getString("nou");
        afficher[7]=rs.getString("dateD");
        afficher[8]=rs.getString("dateF");
        
        afficher[9]=rs.getString("filière");
        afficher[10]=rs.getString("service");
        afficher[11]=rs.getString("direction");
        afficher[12]=rs.getString("etablissement");
        afficher[13]=rs.getString("encadreur");
        afficher[14]=rs.getString("idstagiaire");
        i++;
        model.addRow(afficher);
        }
           txtResultat_trouver.setText(i + ":Resultat trouver");
           tableStagiaire.setModel(model);
           con.close();
           
             // Appliquer le renderer personnalisé aux colonnes du nom et de la date de fin
       

        
            }catch (Exception e) {
                e.printStackTrace();
                    
                    }
        }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anciens_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anciens_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anciens_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anciens_Stagiaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anciens_Stagiaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableStagiaire;
    private javax.swing.JLabel txtResultat_trouver;
    private javax.swing.JTextField txtrechercheStagiaire;
    private javax.swing.JTextField txtrechercheStagiaire1;
    // End of variables declaration//GEN-END:variables
}
